const test=require('node:test'),assert=require('node:assert/strict'),C=require('../core.js');
function perfect(mode='classic',date=new Date('2026-10-09T12:00:00')){const r=new C.Round(mode,C.daily(date));while(!r.over){const t=C.target(Math.min(r.elapsed+.02,r.duration),mode,mode==='daily'?r.challenge.seed:0,r.challenge.variant);r.x=t.x-t.wind;r.y=t.y;r.update(.02,true)}return r}
test('default progress and corrupt saves are safely handled',()=>{const s=C.sanitize({version:1,coins:-2,best:Infinity,theme:'missing',owned:['fake','mint'],unlocked:['fake'],settings:{music:false}});assert.equal(s.coins,0);assert.equal(s.best,0);assert.equal(s.theme,'mint');assert.deepEqual(s.owned,['mint']);assert.equal(s.settings.music,false);assert.equal(C.sanitize(null).mops,1);assert.equal(C.sanitize({version:99}).coins,0)});
test('ellipse collision checks both axes',()=>{assert(C.hit(220,257,220,257));assert(!C.hit(290,257,220,257));assert(!C.hit(220,342,220,257))});
test('perfect classic round reaches timer and yields points and coins',()=>{const r=perfect();assert.equal(r.elapsed,45);assert.equal(r.accuracy,100);assert(r.score>8000);assert(r.coins>400);assert.equal(r.mess,0);const s=C.initial(),p=C.settle(s,r);assert.equal(s.games,1);assert.equal(s.best,r.score);assert(s.unlocked.includes('clean'));assert(p.achievements.length>=4)});
test('misses end run, silence does not earn points',()=>{const r=new C.Round();r.x=0;r.y=0;while(!r.over)r.update(.05,true);assert(r.elapsed<10);assert.equal(r.score,0);assert.equal(r.mess>=100,true);const silent=new C.Round();while(!silent.over)silent.update(.05,false);assert.equal(silent.elapsed,45);assert.equal(silent.coins,0);assert.equal(silent.accuracy,0)});
test('clean streak resets on release, and max streak survives',()=>{const r=new C.Round();for(let i=0;i<200;i++){const t=C.target(r.elapsed+.02);r.x=t.x;r.y=t.y;r.update(.02,true)}assert.equal(r.combo,2);r.update(.02,false);assert.equal(r.combo,1);assert(r.maxStreak>=3.9)});
test('splash insurance rescues only once and grants protection',()=>{const r=new C.Round();r.shield=true;r.x=0;r.y=0;r.mess=99.9;r.update(.1,true);assert.equal(r.shield,false);assert.equal(r.mess,40);assert.equal(r.shieldTime,3);r.update(.1,true);assert.equal(r.mess,40);while(!r.over)r.update(.1,true);assert(r.mess>=100)});
test('theme purchases cannot overdraft and re-equipping is free',()=>{const s=C.initial();assert.equal(C.purchaseTheme(s,'neon'),false);s.coins=400;assert(C.purchaseTheme(s,'neon'));assert.equal(s.coins,50);assert.equal(s.theme,'neon');assert(C.purchaseTheme(s,'mint'));assert.equal(s.coins,50);assert.equal(C.purchaseTheme(s,'fake'),false)});
test('daily seed and movement are reproducible and date-specific',()=>{const d=new Date('2026-10-09T12:00:00'),a=C.daily(d),b=C.daily(d);assert.deepEqual(a,b);assert.notEqual(a.seed,C.daily(new Date('2026-10-10T12:00:00')).seed);assert.deepEqual(C.target(5,'daily',a.seed,a.variant),C.target(5,'daily',b.seed,b.variant))});
test('daily completion bonus and achievement rewards cannot repeat',()=>{const date=new Date('2026-10-09T12:00:00'),s=C.initial(),r=perfect('daily',date);const a=C.settle(s,r,date);assert.equal(a.dailyBonus,200);assert.equal(s.dailyWins,1);const coins=s.coins,b=C.settle(s,r,date);assert.equal(b.dailyBonus,0);assert.equal(s.dailyWins,1);assert.equal(b.achievements.length,0);assert.equal(s.coins-coins,r.coins);assert.deepEqual(C.unlock(s),[])});
test('unfinished daily from previous date cannot claim todays bonus',()=>{const s=C.initial(),r=perfect('daily',new Date('2026-10-09T12:00:00'));assert.equal(C.settle(s,r,new Date('2026-10-10T12:00:00')).dailyBonus,0)});
test('daily rewards prevent repeats, advance, and restart after a gap',()=>{const s=C.initial(),d=new Date('2026-10-09T12:00:00');assert.equal(C.claim(s,d),50);assert.equal(C.claim(s,d),0);assert.equal(C.claim(s,new Date('2026-10-10T12:00:00')),75);assert.equal(C.claim(s,new Date('2026-10-12T12:00:00')),50);assert.equal(s.reward.streak,1)});
test('reward cycle wraps after day seven and blocks clock rollback',()=>{const s=C.initial();for(let i=1;i<=8;i++)C.claim(s,new Date(2026,9,i,12));assert.equal(s.reward.streak,8);assert.equal(C.rewardInfo(s,new Date(2026,9,8,12)).index,0);assert.equal(C.claim(s,new Date(2026,9,7,12)),0)});
test('month/year boundaries preserve consecutive daily rewards',()=>{const s=C.initial();C.claim(s,new Date(2026,11,31,12));assert.equal(C.claim(s,new Date(2027,0,1,12)),75)});
